version: "3"
services:
  mongo:
    # replace username/repo:tag with your name and image details
    image: mongo
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8080:9000"
    networks:
      - webnet
    mongo-express:
    image: mongo-express
    restart: always 
    ports: 
      - "8080:3000
    networks:
      - webnet: